# Project: Pilha com Vetor
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o pilha.o
LINKOBJ  = main.o pilha.o
LIBS     = -L"D:/ESoft/Dev-Cpp/TDM-GCC-64/lib" -L"D:/ESoft/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/include" -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/include" -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/ESoft/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Pilha com Vetor.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\ESoft\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

pilha.o: pilha.c
	$(CC) -c pilha.c -o pilha.o $(CFLAGS)
